parameters:
  osName: ''
  testFramework: ''
  configuration: ''

steps:
<<<<<<< HEAD
=======
- task: PowerShell@2
  displayName: 'Check Ingored File'
  inputs:
    filePath: tools/CheckIgnoredFile.ps1

>>>>>>> e5fcd5c7b105c638909ca50ef4370d71fce2137e
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Build /p:Configuration=${{ parameters.configuration }};TestFramework=${{ parameters.testFramework }};PullRequestNumber=$(System.PullRequest.PullRequestNumber)'

- template: publish-artifacts-steps.yml
  parameters:
<<<<<<< HEAD
    artifactName: build-${{ parameters.osName }}
=======
    artifactName: build-${{ parameters.osName }}
>>>>>>> e5fcd5c7b105c638909ca50ef4370d71fce2137e
