// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Class for CheckServiceProviderAvailabilityInput
    /// </summary>
    public partial class PSCheckServiceProviderAvailabilityInput
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PSCheckServiceProviderAvailabilityInput class.
        /// </summary>
        public PSCheckServiceProviderAvailabilityInput()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PSCheckServiceProviderAvailabilityInput class.
        /// </summary>
<<<<<<< HEAD
        /// <param name="peeringServiceLocation">Gets or sets the
        /// PeeringServiceLocation</param>
        /// <param name="peeringServiceProvider">Gets or sets the
        /// PeeringServiceProvider</param>
=======
        /// <param name="peeringServiceLocation">Gets or sets the peering
        /// service location.</param>
        /// <param name="peeringServiceProvider">Gets or sets the peering
        /// service provider.</param>
>>>>>>> e5fcd5c7b105c638909ca50ef4370d71fce2137e
        public PSCheckServiceProviderAvailabilityInput(string peeringServiceLocation = default(string), string peeringServiceProvider = default(string))
        {
            PeeringServiceLocation = peeringServiceLocation;
            PeeringServiceProvider = peeringServiceProvider;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
<<<<<<< HEAD
        /// Gets or sets the PeeringServiceLocation
=======
        /// Gets or sets the peering service location.
>>>>>>> e5fcd5c7b105c638909ca50ef4370d71fce2137e
        /// </summary>
        [JsonProperty(PropertyName = "peeringServiceLocation")]
        public string PeeringServiceLocation { get; set; }

        /// <summary>
<<<<<<< HEAD
        /// Gets or sets the PeeringServiceProvider
=======
        /// Gets or sets the peering service provider.
>>>>>>> e5fcd5c7b105c638909ca50ef4370d71fce2137e
        /// </summary>
        [JsonProperty(PropertyName = "peeringServiceProvider")]
        public string PeeringServiceProvider { get; set; }

    }
}
